### ISSUE TITLE
maintainance pull request search pattern feature

### ISSUE THREAD

**Issue by Konfekt** [mileszs/ack.vim#147]
Hello, how can one apply for maintenance ? I'd like to open a pull request that optionally turns the last Ack search pattern likewise into the last Vim search pattern.

**Comment by ches** [comment]
Doing some housekeeping on issues and this is an old one… I'm not sure if you're still interested, I think you said elsewhere awhile ago that you may not have the bandwidth anymore. @mileszs still has the administrative control so if you are interested, comment here and he can probably help make it happen. I'm going to close for now but feel free to follow up.

If you do still have that feature sitting around somewhere, feel free to submit a PR either way 😉 

For me, I'd be glad to have help from another maintainer—I can only find time to give ack.vim attention every few months at best. It has its minor imperfections but most of them don't interfere with my workflow significantly, so they're low priority. But I'm otherwise still happy to respond to issues and review PRs on a best-effort basis. If there are others that want to pitch in with maintenance, then the issues and PRs may get closed faster.
