### ISSUE TITLE
quickfix window grows when opening results in vsplit or tab

### ISSUE THREAD

**Issue by haolian9** [mileszs/ack.vim#150]
After `:Ack Controller`, I get 
![1](https://cloud.githubusercontent.com/assets/6236829/5770614/ffa94594-9d67-11e4-9e4e-98028715bfaa.png),
in quickfix window use `v` to open a search result with vertical split window, it works well.
But if the vertical window more than 2, every time use `v`, the quickfix window increase, like 
![2](https://cloud.githubusercontent.com/assets/6236829/5770658/b11c2ec2-9d68-11e4-83d0-a9a2a9c84e4e.png) and 
![3](https://cloud.githubusercontent.com/assets/6236829/5770666/dd4d544e-9d68-11e4-8ecc-049bc032b986.png) and 
![4](https://cloud.githubusercontent.com/assets/6236829/5770673/046a0aae-9d69-11e4-8bca-4bfa644434d5.png)

**Comment by gaohaoliang** [comment]
Maybe I forget to write out my question: *why quickfix window incresed when vertical split window more than 2 ?*

**Comment by ches** [comment]
You're right, and this is annoying.

I've fixed it on the [preserve-list-size][1] branch—just for sake of a quick fix I've removed the ability to configure the `v` and `gv` list window mappings, so this is going to need a bit more work before I can merge it to master, but if you don't care about controlling exactly what those mappings do then please give it a try!

The way the mappings configuration is handled is pretty silly really, I'm going to redo that completely I think but I'll need to take some steps for backwards compatibility or do a major version bump, so it'll be a little longer before I can finish this.

[1]: https://github.com/mileszs/ack.vim/tree/preserve-list-size

**Comment by ches** [comment]
I'll of course leave this issue open and update it when the fix gets merged to mainline.

**Comment by QMonkey** [comment]
Same problem in tab window.

**Comment by Nebuchadrezzar** [comment]
Any chance this is going to enter master soon?

**Comment by eldemcan** [comment]
Looking forward for this fix as well. It is quite annoying in terms of usability. Is there any workaround for that ?

**Comment by maximus8891** [comment]
It'd be nice to have the fix in master.

**Comment by Integralist** [comment]
👋🏻 I see a bunch of issues raised that seem to just be gathering tumbleweed, even though they appear to be issues worth fixing. I don't believe the project is unmaintained so is there anything users can do to help the maintainer get these issues resolved?

I imagine opening PRs would be one approach and contributing fixes, but I can see (just as an example) another issue https://github.com/mileszs/ack.vim/pull/142 that I have where someone actually opened a PR to fix it, but the PR has sat open for the last 7 years 😬. Maybe that happened because the maintainer expects those types of fixes to be incorporated manually by a user 🤔 

Maintaining free software without getting paid for it is hard (especially when you've got a life to live), so it would be nice to get a clearer understanding of what's expected/needed from the maintainer on this project. ❤️

**Comment by haolian9** [comment]
even after 7 years, I still did not learn vimscript so that i can send a PR; and seems this issue nobody cares, I am closing this issue from my side
