### ISSUE TITLE
Perl Error

### ISSUE THREAD

**Issue by carlitux** [mileszs/ack.vim#163]
I am getting this only when using with tmux.

|| perl: warning: Setting locale failed.
|| perl: warning: Please check that your locale settings:
|| 	LC_ALL = "",
|| 	LC_CTYPE = "UTF-8",
|| 	LC_MESSAGES = "",
|| 	LC_NUMERIC = "en_US.utf8",
|| 	LANG = "en_US.UTF-8"
||     are supported and installed on your system.
|| perl: warning: Falling back to the standard locale ("C").

**Comment by ches** [comment]
Sorry this went without a response for so long, I somehow never saw it until now.

This looks like it's an issue coming straight from `ack`, i.e. if you ran an `ack` command outside of Vim you'd get the same errors. Given that and that this issue is so old, I'm going to close it, but if you still have this problem and can verify that it only happens when using ack.vim, please do re-open.

**Comment by lzxin1** [comment]
if you are using zsh, edit `.zshrc`, otherwise edit `.bashrc`
```
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```
it works for me

**Comment by wesalvaro** [comment]
That messed up unicode in my terminal for some reason.  🤷‍♂️  
Instead, just this line without the `.UTF-8` worked for me:

```
export LC_ALL=en_US
```
