### ISSUE TITLE
"Searching ..." indefinitely if result(s) are found when using MacVim

### ISSUE THREAD

**Issue by solidcell** [mileszs/ack.vim#62]
It continues saying "Searching ..." if something should have been found, and returns a blank quickfix if there is nothing found (as it should).  This is an issue with the current state of master (e93f693).  It works fine in vim, but is an issue in MacVim.

**Comment by morr** [comment]
@kassio it is still happening
![no name - vim 2015-01-22 15-13-31](https://cloud.githubusercontent.com/assets/134610/5855425/4330a6be-a249-11e4-8ed5-9e90b4e857a7.jpg)

![no name - vim 2015-01-22 15-12-44](https://cloud.githubusercontent.com/assets/134610/5855414/265b532c-a249-11e4-9d4a-243cba674552.jpg)
![no name - - vim 2015-01-22 15-13-02](https://cloud.githubusercontent.com/assets/134610/5855420/3289a342-a249-11e4-9095-abaeef704b4e.jpg)

**Comment by morr** [comment]
In console vim Ack works perfectly
![2 vim vim 2015-01-22 15-16-04](https://cloud.githubusercontent.com/assets/134610/5855468/a63139b8-a249-11e4-8281-d44b66d1b3d2.jpg)

**Comment by morr** [comment]
@kassio it does not work with `set noguipty` in `vimrc`

**Comment by slamflipstrom** [comment]
@kassio this is an issue for me as well. It works fine in vim, but not MacVim.

**Comment by ches** [comment]
I'll re-open for visibility since others are still seeing this problem. I've not been able to replicate in GUI MacVim, though I normally use it in the console so I confess that it's unlikely to give me an itch to investigate more, I'd invite others to research potential cause and fixes.

@slamflipstrom or others still following, are you using the default `g:ackprg` or any custom search program/options? Since ack.vim largely works atop Vim's existing grep features, could you try some tests using the built-in features and see if you observe any problems? See `:help grep`.

**Comment by slamflipstrom** [comment]
@ches I'm unable to replicate the issue at this time. I discovered I was using an older version of MacVim,  so that may have been the culprit.

**Comment by ches** [comment]
@slamflipstrom Great, thank you for following up.

@solidcell and @morr please leave a comment if you still encounter this issue with recent versions, and I'll reopen again.

**Comment by tsujigiri** [comment]
I have this issue for ages. Sometimes it works, sometimes it doesn't. Most of the time it does this the first try I search something and works on the second. Same in vim and neovim on Linux.
