### ISSUE TITLE
Empty quickfix results

### ISSUE THREAD

**Issue by amcsi** [mileszs/ack.vim#82]
When using :Ack, the results are displayed very quickly in the focused window, but the quickfix list is always empty.

I'm using vim in cygwin in windows and the ack command is a file in my /usr/bin starting with  #!/usr/bin/env perl
and having the entire contents of ack.pl in it

**Comment by micahwedemeyer** [comment]
Getting rid of the  wookiehangover/jshint.vim plugin fixed it for me.

**Comment by amcsi** [comment]
Anyone with this same problem: have you tried specifying the path at the end of the vim command? E.g. instead of calling `:Ack stringToSearch`, try ':Ack stringToSearch .` specifying (dot). I do remember that in certain environments, specifying the path eased certain problems.

**Comment by ches** [comment]
Okay folks, since this is an old issue that apparently had several unrelated causes, sometimes user error (like no `ack` executable present :innocent:), etc., I'm going to close this in the interest of collecting fresher bug reports if some people are still having a problem like this.

To summarize:

- Some badly-behaving plugins have been identified that conflict: see #34 for haskellmode-vim and wookiehangover/jshint.vim#42 for jshint.vim.
- ack.vim has changed a good deal over the time this issue has been open, please update to the latest version, preferably from git but latest zipball release should be fine too.

If you're still experiencing a similar problem, please open a new issue and:

- Share your full Vim configuration, including plugin list.
- Please note if you're using tmux and if behavior is any different without it, so we can troubleshoot differences in shell environment.
- Try location list versions of commands (`:LAck`) and report if there is any difference in behavior. Note that if you're using ack.vim's support for Dispatch, location list isn't supported—please test with `let g:ack_use_dispatch = 0` (which is currently the default setting).

Thanks for your patience and for everyone who went to the trouble of tracking down plugin conflicts.

@amcsi if you're still getting the invalid expression error could you please open a separate issue for that?

**Comment by PeteW** [comment]
I was still seeing the issue. GVIM 7.4 windows, nerdtree, dbext and various other plugins I rely on for IDE.
My solution was to ensure the working dir matched the git root of the current buffer. That way the ack command is running from the root of my current project.

[More info](http://inlehmansterms.net/2014/09/04/sane-vim-working-directories/)

`
" set working directory to git project root
" or directory of current file if not git project
function! SetProjectRoot()
  " default to the current file's directory
  lcd %:p:h
  let git_dir = system("git rev-parse --show-toplevel")
  " See if the command output starts with 'fatal' (if it does, not in a git repo)
  let is_not_git_dir = matchstr(git_dir, '^fatal:.*')
  " if git project, change local directory to git project root
  if empty(is_not_git_dir)
    lcd `=git_dir`
  endif
endfunction
" follow symlink and set working directory
autocmd BufRead * call SetProjectRoot()
`
